data:
  name: cora_ml
  training_nodes_per_class: 20

model:
  hidden_channels: 64

training:
  lr: 0.001
  batch_size: 32
  max_epochs: 3000
  weight_decay: 0.001

voting:
  repeats: 100000
  batch_size: 25

noise:
  P_min: [0.01, 0.06]
  P_max: [0.01, 0.06]
  P_step: [0.0, 0.0]

radius:
  R_min: [1, 1]
  R_max: [8, 22]
  R_step: [1, 1]

confidence_level: 0.99
