dataset: cora_ml

model:
  hidden_channels: [16, 16]

training:
  lr: 0.01
  max_epochs: 50

noise:
  P_min: (0.01, 0.06)
  P_max: (0.01, 0.06)
  P_steps: (0.0, 0.0)

radius:
  R_min: (1, 1)
  R_max: (8, 22)
  R_step: (1, 1)