data:
  name: hiv
  min_required_edge_flips: 20
  split_proportions: [0.7, 0.2, 0.1]
  num_features: 69
  num_classes: 2

model:
  architecture: 'gcn'
  hidden_channels: [16, 16]
  dropout: 0.0

training:
  lr: 0.001
  max_epochs: 200
  batch_size: 32
  weight_decay: 0.001

voting:
  repeats: 100000
  batch_size: 50

noise:
  P_min: [0.01, 0.01]
  P_max: [0.1, 0.1]
  P_step: [0.02, 0.02]

radius:
  R_min: [1, 1]
  R_max: [7, 7]
  R_step: [1, 1]

confidence_level: 0.99
