data:
  source: tudataset
  name: MUTAG
  train_split: 0.8
  test_split: 0.1

model:
  architecture: 'gcn'
  hidden_channels: [64]
  dropout: 0.5
  use_positional_encoding: False

training:
  lr: 0.001
  decay: True
  max_epochs: 500
  batch_size: 32
  weight_decay: 0.001
  train_with_noise: True
  p: [0.4, 0.2]

voting:
  repeats: 100000
  batch_size: 50

noise:
  P_min: [0.04, 0.2]
  P_max: [0.04, 0.2]
  P_step: [0, 0]
