data:
  name: synthetic
  graphs_per_class: 2000
  size_of_community: 20
  number_of_communities: 3
  split_proportions: [0.8, 0.175, 0.025]

model:
  hidden_channels: [16, 16]

training:
  lr: 0.001
  max_epochs: 3000
  batch_size: 32
  weight_decay: 0.001

voting:
  repeats: 100000
  batch_size: 50

noise:
  P_min: [0.01, 0.01]
  P_max: [0.1, 0.1]
  P_step: [0.02, 0.02]

radius:
  R_max: [7, 7]

confidence_level: 0.99
