## Configuration File
dataset: synthetic
graphs_per_class: 300
community_sizes: [20, 20, 20]
sbm_parameters: [[0.2, 0.02, 0.02], [0.02, 0.3, 0.02], [0.02, 0.02, 0.4]]
data_split: [0.7, 0.2, 0.1]
optimisation:
  lr: 0.01
  max_epochs: 40
  hidden_channels: 32
  batch_size: 32
certification:
  perturbation: bernoulli
  sample_eval: 1000
  parameter_list: [0.05, 0.1]
  batch_size: 200