## Configuration File
dataset: synthetic
graphs_per_class: 300
community_sizes: [20, 20, 20]
sbm_parameters: [[0.2, 0.02, 0.02], [0.02, 0.2, 0.02], [0.02, 0.02, 0.2]]
data_split: [0.7, 0.2, 0.1]
optimisation:
  lr: 0.01
  max_epochs: 40
  hidden_channels: [16, 16]
  batch_size: 32
certification:
  sample_eval: 1000
  batch_size: 200
  alpha_parameter_min: 0.01
  alpha_parameter_max: 0.1 #0.2
  alpha_parameter_step: 0.02 # 0.01
  r_max: 7
  confidence_level: 0.99